### ISSUE TITLE
Do not use dev-master as version for a tagged release

### ISSUE THREAD

**Issue by c33s** [Drenso/IcalBundle#2]
if you require a third party lib via composer use:
- an explicit version: `kigkonsult/icalcreator: 2.22`
- a version contraint if the package uses [semver](http://semver.org/): `kigkonsult/icalcreator: ~2.22` [see versions](https://getcomposer.org/doc/articles/versions.md)
- use the @stable syntax: `kigkonsult/icalcreator: @stable`

but do not use `dev-master` if not really necessary because this dependency couldn't be met in a default composer project because of the `minimum-stability: stable` [setting](https://getcomposer.org/doc/04-schema.md#minimum-stability)

**Comment by tobias-93** [comment]
@c33s Thank you for your feedback. I agree with you, however please see the discussions on the github of iCalcreator, most importantly https://github.com/iCalcreator/iCalcreator/issues/7 and https://github.com/iCalcreator/iCalcreator/issues/21. Since there are no releases, we cannot depend on a stable version as that will break the bundle. I will monitor the process on these issues and put a stable version in the composer.json as soon as it is available.

**Comment by c33s** [comment]
hm, i see. not that cool. i commented at iCalcreator issue, hope they add tags.

if not, maybe having  a look at a different lib like https://github.com/markuspoerschke/iCal would be an option.
another option would be to fork iCalcreator to self-control the tags

**Comment by tobias-93** [comment]
I'm closing this, as this bundle is abandoned anyway. Please use https://github.com/BorisMorel/IcalBundle instead. For a PR which should fix this issue for that bunde, see https://github.com/BorisMorel/IcalBundle/pull/30.
